openapi: 3.0.0
info:
  title: 공장관리 API
  version: 1.0.0
paths:
  /api/v1/factory:
    get:
      summary: Retrieve all factories
      tags:
        - Factory
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factory'
  /api/v1/factory/{id}:
    get:
      summary: Retrieve a factory by ID
      tags:
        - Factory
      parameters:
        - name: id
          in: path
          description: ID of the factory to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factory'
  /api/v1/factory/{id}/buyOrigin:
    post:
      summary: Buy an origin for a factory
      tags:
        - Factory
      parameters:
        - name: id
          in: path
          description: ID of the factory to buy an origin for
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OriginDto'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factory'
        '400':
          description: Bad Request
          content:
            text/plain:
              example: 'Error: {error message}'
  /api/v1/factory/{id}/useOrigin:
    post:
      summary: Use an origin for a factory
      tags:
        - Factory
      parameters:
        - name: id
          in: path
          description: ID of the factory to buy an origin for
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OriginDto'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factory'
        '400':
          description: Bad Request
          content:
            text/plain:
              example: 'Error: {error message}'
  /api/v1/factory/{id}/success:
    get:
      summary: Use an origin for a factory
      tags:
        - Factory
      parameters:
        - name: id
          in: path
          description: ID of the factory to buy an origin for
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
  /api/v1/factory/{id}/failure:
    get:
      summary: Use an origin for a factory
      tags:
        - Factory
      parameters:
        - name: id
          in: path
          description: ID of the factory to buy an origin for
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
  /login:
    post:
      summary: Login and retrieve user information
      tags:
        - Authentication
      requestBody:
        description: Login information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDtoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginDtoResponse'
  /logout:
    post:
      summary: Login and retrieve user information
      tags:
        - Authentication
      requestBody:
        description: Login information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDtoRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginDtoResponse'
components:
  schemas:
    LoginDtoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
          description: User name
    LoginDtoRequest:
      type: object
      properties:
        name:
          type: string
          description: User name
    Factory:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
          description: Factory name
        income:
          type: integer
          description: Income
        outcome:
          type: integer
          description: Outcome
        asset:
          type: integer
          description: Asset
        totalCount:
          type: integer
          description: Total count
        successCount:
          type: integer
          description: Success count
        status:
          type: boolean
          description: Status
      required:
        - name
    OriginDto:
      type: object
      properties:
        id:
          type: integer
        count:
          type: integer