apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app
  name: webclient-config
data:
  storage.url: "http://app-service/api/v1"
  spring.kafka.topic: "storage"
  spring.kafka.bootstrap-servers: "kafka-service:9092"