apiVersion: v1
kind: ConfigMap
metadata:
  namespace: app
  name: webclient-config
data:
  storage.url: "http://storage-service/api/v1"
  spring.kafka.topic: "storage"
  spring.kafka.bootstrap-servers: "kafka-service:9092"
  management.zipkin.tracing.endpoint: "http://zipkin-svc.zipkin.svc:9411/api/v2/spans"